language: python
python:
  - "3.7-dev"

cache: pip

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=facial_attendance.settings
  - export PGHOST=localhost
  - export PGPORT=5432

install:
  - pip install -r requirements.txt
  - pip install -q psycopg2
  - pip install -q coveralls

before_script:
  - psql -c "create database travis_ci_test;" -U postgres

script:
  - pycodestyle .
  - python manage.py makemigrations && python manage.py migrate
  - coverage run manage.py test

after_script:
  - coverage report
  - coveralls
